### ISSUE TITLE
Не работает синхронизация

### ISSUE THREAD

**Issue by adlordy** [adlordy/report-generator#7]
В списки на сервере добавили новые проекта. Нажал Sync -  Error occured. 
В cmd:
fail: Microsoft.AspNetCore.Server.Kestrel[13]
     Connection id "0HKVC4GMJVFHG": An unhandled exception was thrown by the ap
plication.
System.Xml.XmlException: Data at the root level is invalid. Line 45121, position
8.
  at System.Xml.XmlTextReaderImpl.Throw(Exception e)
  at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
  at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
  at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
  at System.Xml.XmlTextReaderImpl.Read()
  at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
  at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
  at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
  at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
  at System.Xml.Linq.XDocument.Load(String uri)
  at ReportGenerator.Controllers.DataController.<LoadFromServer>d__20.MoveNext(
) in C:\Users\ildar.khabibullin\AppData\Roaming\WindowTitleMonitor\report-genera
tor\Controllers\DataController.cs:line 214
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
  at ReportGenerator.Controllers.DataController.<LoadFromServer>d__20.MoveNext(
) in C:\Users\ildar.khabibullin\AppData\Roaming\WindowTitleMonitor\report-genera
tor\Controllers\DataController.cs:line 218
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
  at ReportGenerator.Controllers.DataController.<Sync>d__19.MoveNext() in C:\Us

**Comment by adlordy** [comment]
Удаление файлов исправляет ситуацию
